DROP TABLE IF EXISTS Proveedor CASCADE;
DROP TABLE IF EXISTS Producto CASCADE;
DROP TABLE IF EXISTS Ciudad CASCADE;
DROP TABLE IF EXISTS Cliente CASCADE;
DROP TABLE IF EXISTS Pedido CASCADE;
DROP TABLE IF EXISTS Factura CASCADE;
DROP TABLE IF EXISTS Empleado CASCADE;
DROP TABLE IF EXISTS Categoria CASCADE;
DROP TABLE IF EXISTS Auditoria_Pedido CASCADE;

--DDL--

CREATE TABLE Proveedor (
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100) NOT NULL,
	CUIT INT UNIQUE,
	Fecha_alta TIMESTAMP DEFAULT NOW()
    );

ALTER TABLE Proveedor
ADD Email VARCHAR(100);

ALTER TABLE Proveedor
DROP COLUMN Email;

CREATE TABLE Categoria (
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100)
    );

CREATE TABLE Producto (
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100),
	Precio DECIMAL CHECK(Precio > 0),
	Stock INT CHECK(Stock > 0),
	IdCategoria INT,

	FOREIGN KEY (IdCategoria)
	    REFERENCES Categoria(ID)
    );

CREATE TABLE Ciudad (
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100)
    );

CREATE TABLE Cliente (
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100),
	Apellido VARCHAR (100),
	Edad INT CHECK(Edad >= 18),
	Email VARCHAR(100) NOT NULL UNIQUE,
	IdCiudad INT,

	FOREIGN KEY (IdCiudad)
	    REFERENCES Ciudad(ID)
    );

CREATE TABLE Pedido (
    ID INT PRIMARY KEY,
	Fecha TIMESTAMP,
	IdCliente INT,

	FOREIGN KEY (IdCliente)
	    REFERENCES Cliente(ID)
	);

CREATE TABLE Factura (
    ID INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	FechaVencimiento TIMESTAMP
    );

CREATE TABLE Empleado (
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100),
	Supervisor INT,

	FOREIGN KEY (Supervisor)
	    REFERENCES Empleado(ID)
    );

--DML--

INSERT INTO Factura (FechaVencimiento) VALUES
(NOW());

INSERT INTO Ciudad (ID, Nombre) VALUES
(1, 'Buenos Aires'),
(2, 'Madrid'),
(3, 'Montevideo'),
(4, 'Santiago'),
(5, 'Lima'),
(6, 'Quito'),
(7, 'Bogota'),
(8, 'Asuncion'),
(9, 'La Paz'),
(10,'Caracas');

INSERT INTO Cliente (ID, Nombre, Apellido, Edad, Email, IdCiudad) VALUES
(1, 'Juan', 'Lopez', 18, 'juanlopez@gmail.com', 2),
(2, 'Rodrigo', 'Gonzalez', 24, 'rodrigogonzalez@gmail.com', 1),
(3, 'Esteban', 'Caputo', 31, 'estebancaputo@gmail.com', 1),
(4, 'Arturo', 'Benitez', 34, 'arturobenitez@gmail.com', 4),
(5, 'Wilbert', 'Jimenez', 50, 'wilbertjimenez@gmail.com', 5),
(6, 'Pablo', 'Lichtig', 42, 'pablolichtig@gmail.com', 1),
(7, 'Alejandro', 'Dangelo', 55, 'alejandrodangelo@gmail.com', 1);

INSERT INTO Pedido (ID, Fecha, IdCliente) VALUES
(1, NOW(), 1),
(2, '2019-08-21 17:00:00', 3),
(3, '2021-05-04 14:00:00', NULL),
(4, '2024-09-14 18:00:00', 7),
(5, '2022-11-22 23:00:00', 5),
(6, '2018-03-28 11:00:00', 7),
(7, '2023-06-21 19:00:00', 2),
(8, '2025-07-16 15:00:00', 6),
(9, '2020-02-06 13:00:00', 3),
(10, '2017-12-11 14:00:00', 7),
(11, '2016-10-01 20:00:00',6);

SELECT * FROM Cliente;

SELECT DISTINCT ci.ID, ci.Nombre, COUNT(ci.ID)
FROM Cliente cl INNER JOIN Ciudad ci ON ci.ID = cl.IdCiudad
GROUP BY ci.ID;

INSERT INTO Categoria (ID, Nombre) VALUES
(1, 'Utiles'),
(2, 'Electronicos'),
(3, 'Ropa'),
(4, 'Comida'),
(5, 'Ferreteria');

INSERT INTO Producto (ID, Nombre, Precio, Stock, IdCategoria) VALUES
(1, 'Lapiz', 400, 20, 1),
(2, 'Tablet', 300000, 3, 2),
(3, 'Campera', 180000, 18, 3),
(4, 'Medialuna', 300, 20, 4),
(5, 'Cuaderno', 1000, 12, 1),
(6, 'Banana', 500, 15, 4),
(7, 'Ventilador', 1500, 4, 2),
(8, 'Mantel', 2000, 11, 3),
(9, 'Celular', 120000, 6, 2),
(10, 'Zapatillas', 105000, 7, 3),
(11, 'Heladera', 200000, 5, 2),
(12, 'Horno', 190000, 7, 2),
(13, 'Auriculares', 290000, 8, 2);

INSERT INTO Empleado (ID, Nombre, Supervisor) VALUES
(1, 'José', 2),
(2, 'Raúl', 1);

SELECT * FROM Producto
WHERE Precio > 500;

SELECT * FROM Producto
WHERE Precio BETWEEN 500 AND 2000;

SELECT * FROM Cliente
WHERE Nombre LIKE 'A%';

SELECT COUNT(*) FROM Producto;

SELECT SUM(Stock) AS Suma_stock_total FROM Producto;

SELECT AVG(Precio) AS Promedio_precios FROM Producto;

SELECT MIN(Precio) AS Minimo, MAX(Precio) AS Maximo FROM Producto;

SELECT * FROM Pedido p
INNER JOIN Cliente c ON c.ID = p.IdCliente;

SELECT * FROM Cliente c
LEFT JOIN Pedido p ON p.IdCliente = c.ID WHERE p.id IS NULL;

SELECT * FROM Cliente c
FULL OUTER JOIN Pedido p ON p.IdCliente = c.ID WHERE p.ID IS NULL OR c.ID IS NULL;

SELECT e.Nombre AS empleado, s.Nombre AS supervisor FROM Empleado AS e 
LEFT JOIN Empleado AS s ON e.Supervisor = s.ID;

SELECT c.ID, c.Nombre, COUNT(p.ID) AS Cantidad_pedidos
FROM Cliente c LEFT JOIN Pedido p ON p.IdCliente = c.ID
GROUP BY c.ID, c.Nombre ORDER BY c.ID;

SELECT c.ID, c.Nombre, COUNT(p.ID)
FROM Categoria c LEFT JOIN Producto p ON p.IdCategoria = c.ID
GROUP BY c.ID, c.Nombre ORDER BY c.ID;
SELECT c.ID, c.Nombre, COUNT(p.ID) AS Cantidad_productos
FROM Categoria c LEFT JOIN Producto p ON p.IdCategoria = c.ID
GROUP BY c.ID
HAVING COUNT(p.ID) > 5;

SELECT * FROM Producto p1
WHERE p1.Precio > (SELECT AVG(p2.Precio) FROM Producto p2);

SELECT * FROM Cliente
WHERE EXISTS (SELECT IdCliente FROM Pedido
WHERE Pedido.IdCliente = Cliente.id);

SELECT * FROM Producto
WHERE NOT Precio > ANY(SELECT Precio FROM Producto);

SELECT * FROM Producto
WHERE Precio >= ALL(SELECT Precio FROM Producto);

SELECT * FROM Pedido
WHERE EXTRACT(YEAR FROM Fecha) = EXTRACT(YEAR FROM CURRENT_DATE);

SELECT * FROM Pedido
WHERE EXTRACT(MONTH FROM Fecha) = 3;

SELECT ID, AGE(Fecha::DATE) FROM Pedido;

SELECT CURRENT_TIMESTAMP;

--VISTAS--

CREATE VIEW VentasPorCliente AS
SELECT c.ID, c.Nombre, COUNT(p.ID) AS Cantidad_pedidos
FROM Cliente c LEFT JOIN Pedido p ON p.IdCliente = c.ID
GROUP BY c.ID, c.Nombre ORDER BY c.ID;

SELECT * FROM VentasPorCliente;

DROP VIEW VentasPorCliente;

--FUNCTION--

CREATE OR REPLACE FUNCTION cantidad_pedidos_cliente(id_cli INT)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE Cantidad INT;
BEGIN
    SELECT COUNT(*)
	INTO Cantidad
	FROM Cliente c LEFT JOIN Pedido p ON p.IdCliente = c.ID
	WHERE c.ID = id_cli;

	RETURN Cantidad;

END;
$$;

SELECT cantidad_pedidos_cliente(7);

CREATE OR REPLACE FUNCTION precio_promedio_categoria(id_cat INT)
RETURNS DECIMAL
LANGUAGE plpgsql
AS $$
DECLARE promedio DECIMAL;
BEGIN
    SELECT COALESCE(AVG(p.Precio), 0)
	INTO promedio
	FROM Producto p RIGHT JOIN Categoria c ON c.ID = p.IdCategoria
	WHERE c.ID = id_cat;

	RETURN promedio;

END;
$$;

SELECT precio_promedio_categoria(3);

CREATE OR REPLACE FUNCTION cliente_con_mas_pedidos()
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE 
    maximo INT;
	cantidad_maxima INT;
BEGIN
    SELECT c.ID, COUNT(p.ID)
	INTO maximo, cantidad_maxima
	FROM Cliente c LEFT JOIN Pedido p ON p.IdCliente = c.ID
    GROUP BY c.ID, c.Nombre ORDER BY COUNT(p.ID) DESC LIMIT 1;

	IF cantidad_maxima = 0 THEN
        RETURN 0;
    END IF;

	RETURN maximo;

END;
$$;

SELECT cliente_con_mas_pedidos();

--PROCEDURE--

CREATE OR REPLACE PROCEDURE mostrar_cliente(id_cli INT)
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE NOTICE '%',
	(SELECT CONCAT('ID: ', ID, ' Nombre: ', Nombre, ' Apellido: ', Apellido)
	FROM Cliente WHERE ID = id_cli);
END;
$$;

CALL mostrar_cliente(7);

CREATE OR REPLACE PROCEDURE mostrar_productos_categoria(id_cat INT)
LANGUAGE plpgsql
AS $$
DECLARE producto_actual RECORD;
BEGIN
    FOR producto_actual IN
	    SELECT ID, Nombre
	    FROM Producto WHERE IdCategoria = id_cat

	LOOP
	    RAISE NOTICE
		'ID: %, Nombre: %',
		producto_actual.ID,
		producto_actual.Nombre;
	END LOOP;

END;
$$;

CALL mostrar_productos_categoria(2);

CREATE OR REPLACE PROCEDURE informe_general()
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE NOTICE 'Cantidad de clientes: %, 
	 Cantidad de Productos: %, 
	 Cantidad de Pedidos: %',
	(SELECT COUNT(*)
	FROM Cliente),
	(SELECT COUNT(*)
	FROM Producto),
	(SELECT COUNT(*)
	FROM Pedido);
	
END;
$$;

CALL informe_general();

--TRIGGER--

CREATE OR REPLACE FUNCTION validar_precio()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.Precio < 0 THEN
	    RAISE EXCEPTION 'El precio no puede ser negativo';
	END IF;

	RETURN NEW;

END;
$$;

CREATE TRIGGER trg_validar_fechas
BEFORE INSERT OR UPDATE
ON Producto
FOR EACH ROW
EXECUTE FUNCTION validar_precio();

--INSERT INTO Producto (ID, Nombre, Precio, Stock, IdCategoria) VALUES (14, 'Leche', -200, 30, 4);
--UPDATE Producto SET Precio = -300000 WHERE Nombre = 'Tablet';

CREATE TABLE Auditoria_Pedido(
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdPedido INT,
    Operacion VARCHAR(20),
    Fecha TIMESTAMP
);

CREATE OR REPLACE FUNCTION registrar_pedido()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
	    INSERT INTO Auditoria_Pedido (IdPedido, Operacion, Fecha) VALUES
		(NEW.ID, 'INSERT', NEW.Fecha);
	END IF;

	IF TG_OP = 'DELETE' THEN
	    INSERT INTO Auditoria_Pedido (IdPedido, Operacion, Fecha) VALUES
		(OLD.ID, 'DELETE', OLD.Fecha);
	END IF;

	IF TG_OP = 'UPDATE' THEN
	    IF OLD.ID <> NEW.ID THEN
	        INSERT INTO Auditoria_Pedido (IdPedido, Operacion, Fecha) VALUES
		    (NEW.ID, 'UPDATE', OLD.Fecha);
		ELSIF OLD.Fecha <> NEW.Fecha THEN
	        INSERT INTO Auditoria_Pedido (IdPedido, Operacion, Fecha) VALUES
		    (OLD.ID, 'UPDATE', NEW.Fecha);
		END IF;
	END IF;

    RETURN NULL;
	
END;
$$;

CREATE TRIGGER trg_auditar
AFTER INSERT OR UPDATE OR DELETE
ON Pedido
FOR EACH ROW
EXECUTE FUNCTION registrar_pedido();

INSERT INTO Pedido (ID, Fecha, IdCliente) VALUES
(12, NOW(), 1);

UPDATE Pedido
SET Fecha = '2025-11-11 18:00:00'
WHERE ID = 12;

DELETE FROM Pedido WHERE ID = 12;

SELECT * FROM Auditoria_Pedido;

CREATE OR REPLACE FUNCTION impedir_borrar_categoria()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.ID IN (SELECT IdCategoria FROM Producto) THEN
	    RAISE EXCEPTION 'La categoria % no se puede borrar porque tiene productos asociados',
		    OLD.Nombre;
	END IF;

	RETURN OLD;

END;
$$;

CREATE TRIGGER trg_validar_borrado_categoria
BEFORE DELETE
ON Categoria
FOR EACH ROW
EXECUTE FUNCTION impedir_borrar_categoria();

--DELETE FROM Categoria WHERE ID = 2;

DELETE FROM Categoria WHERE ID = 5;

SELECT * FROM Categoria;

INSERT INTO Categoria (ID, Nombre) VALUES
(5, 'Ferreteria');

ALTER TABLE Cliente
ADD TotalPedidos INT DEFAULT 0;

CREATE OR REPLACE FUNCTION actualizar_pedidos()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
	    UPDATE Cliente
		SET TotalPedidos = TotalPedidos + 1
		WHERE ID = NEW.IdCliente;
	END IF;

	IF TG_OP = 'DELETE' THEN
	    UPDATE Cliente
		SET TotalPedidos = TotalPedidos - 1
		WHERE ID = OLD.IdCliente;
	END IF;

	IF TG_OP = 'UPDATE' AND OLD.IdCliente <> NEW.IdCliente THEN
	    UPDATE Cliente
		SET TotalPedidos = TotalPedidos - 1
		WHERE ID = OLD.IdCliente;

		UPDATE Cliente
		SET TotalPedidos = TotalPedidos + 1
		WHERE ID = NEW.IdCliente;
	END IF;

	RETURN NULL;

END;
$$;

CREATE TRIGGER trg_actualizacion_pedidos
AFTER INSERT OR UPDATE OR DELETE
ON Pedido
FOR EACH ROW
EXECUTE FUNCTION actualizar_pedidos();

INSERT INTO Pedido (ID, Fecha, IdCliente) VALUES
(12, NOW(), 1),
(13, '2019-08-21 17:00:00', 3),
(14, '2021-05-04 14:00:00', NULL),
(15, '2024-09-14 18:00:00', 7),
(16, '2022-11-22 23:00:00', 5),
(17, '2018-03-28 11:00:00', 7),
(18, '2023-06-21 19:00:00', 2),
(19, '2025-07-16 15:00:00', 6),
(20, '2020-02-06 13:00:00', 3),
(21, '2017-12-11 14:00:00', 7),
(22, '2016-10-01 20:00:00',6);

UPDATE Pedido
SET IdCliente = 1
WHERE ID = 16;

DELETE FROM Pedido WHERE ID = 22;

SELECT * FROM Cliente;

--INJECTIONS--

--EL SIGUIENTE CÓDIGO:
--SELECT * FROM Usuario WHERE Nombre = '"+ nombre +"';
--Es vulnerable porque la base de datos confunde los datos del usuario con instrucciones reales 
--y ejecuta comandos maliciosos

--La SQL Injection se evita mediante consultas parametrizadas, usando un marcador ?.
--Por ejemplo, si un atacante escribe (admin' OR '1'='1) sin consulta parametrizada, devuelve siempre true
--porque 1 = 1 y le da el ok al atacante para entrar sin contraseña. Sin embargo, con consulta parametrizada,
--la única manera de que el atacante pueda entrar, es que el nombre de usuario sea literalmente
--admin' OR '1'='1, lo cual es imposible.

CREATE INDEX idx_email ON Cliente(Email);

CREATE INDEX idx_apellido_nombre ON Cliente(Apellido, Nombre);

--No conviene usar índices cuando se realizan operaciones como insert, update o delete
--porque al tener que buscar en el índice tarda más tiempo en realizarlas, y cuando
--hay pocos datos, porque la base de datos tarda más tiempo en buscar dentro del índice
--que en leer toda la tabla directamente.

--BACKUP--

--Un backup completo crea una copia de toda la base de datos.
--Un backup incremental crea una copia de los cambios que hubo desde el último respaldo.
--Restore es el proceso de recuperar esos datos a partir de las copias.

--Crear backub desde pgAdmin4: Click derecho en la base de datos, Backup, guardar en la computadora.
--Lo mismo para restaurar.

--HOSTING--

--La diferencia entre base local, base remota, hosting administrativo y hosting propio está en dónde
--se guardan los datos y quién administra los servidores.
--En la base local, los datos se almacenan en el disco duro de la computadora físic, mientras que
--en la base remota los datos se almacenan en la nube.
--En el hosting propio, el que compra o alquila un servidor se encarga de todo, mientras que
--en el hosting administrativo se alquila un servidor donde el proveedor se encarga
--del mantenimiento técnico.

--Para conectarse a una BD remota son necesarios:
--Host: Dirección IP o dominio
--Puerto: Canal específico de comunicación
--Usuario: Nombre de la cuenta
--Password: Clave de seguridad
--Database: Nombre específico de la base de datos

--DATA TYPES--
--Nombre: VARCHAR(100)
--FechaNacimiento: TIMESTAMP
--Precio: DECIMAL
--Cantidad: INT
--Email: VARCHAR(100)
--Observaciones: VARCHAR(100)

--La diferencia entre char, varchar y text está en cómo almacenan el texto en el disco y su longitud máxima
--en la computadora.
--CHAR: Longitud fija, el espacio en el disco es siempre el máximo definido, y el rendimiento es muy rápido
--VARCHAR: Longitud variable, sólo los caracteres reales ocupan más de 1 0 2 bytes
--TEXT: Longitud variable hasta 4 GB y rendimiento más lento

--La diferencia entre DATE, TIMESTAMP y TIMESTAMPTZ radica en la precisión del tiempo y en cómo manejan
--las zonas horarias.
--DATE: Almacena únicamente año, mes y día
--TIMESTAMP: Almacena fecha completa incluyendo horas, minutos y segundos
--TIMESTAMPTZ: Incluye la zona horaria además de la fecha completa.

--SIMULACRO FINAL--

DROP TABLE IF EXISTS Biblioteca CASCADE;
DROP TABLE IF EXISTS Empleado CASCADE;
DROP TABLE IF EXISTS Contrato_Empleado CASCADE;
DROP TABLE IF EXISTS Escritor CASCADE;
DROP TABLE IF EXISTS Libro CASCADE;
DROP TABLE IF EXISTS Contrato_Libro CASCADE;
DROP TABLE IF EXISTS Cliente CASCADE;
DROP TABLE IF EXISTS Prestamo CASCADE;
DROP TABLE IF EXISTS Auditoria_Prestamo CASCADE;

CREATE TABLE Biblioteca(
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100)
    );

CREATE TABLE Empleado (
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100)
    );

CREATE TABLE Contrato_Empleado (
    ID INT PRIMARY KEY,
	Inicio TIMESTAMP,
	Fin TIMESTAMP,
	IdEmpleado INT,
	IdBiblioteca INT,

	FOREIGN KEY (IdEmpleado)
	    REFERENCES Empleado(ID),

	FOREIGN KEY (IdBiblioteca)
	    REFERENCES Biblioteca(ID)
    );

CREATE TABLE Escritor(
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100)
    );

CREATE TABLE Libro(
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100),
	StockPrestado INT DEFAULT 0 CHECK (StockPrestado >= 0),
	StockDisponible INT CHECK (StockDisponible >= 0),
	IdEscritor INT NOT NULL,

	FOREIGN KEY (IdEscritor)
	    REFERENCES Escritor(ID)
    );

CREATE TABLE Contrato_Libro (
    ID INT PRIMARY KEY,
	Inicio TIMESTAMP,
	Fin TIMESTAMP CHECK (Fin >= Inicio),
	IdLibro INT,
	IdBiblioteca INT,

	FOREIGN KEY (IdLibro)
	    REFERENCES Libro(ID),

	FOREIGN KEY (IdBiblioteca)
	    REFERENCES Biblioteca(ID)
);

CREATE TABLE Cliente(
    ID INT PRIMARY KEY,
	Nombre VARCHAR(100)
    );

CREATE TABLE Prestamo(
    ID INT PRIMARY KEY,
	Inicio TIMESTAMP,
	Fin TIMESTAMP CHECK (Fin >= Inicio),
	IdCliente INT,
	IdLibro INT,

	FOREIGN KEY (IdCliente)
	    REFERENCES Cliente(ID),

	FOREIGN KEY (IdLibro)
	    REFERENCES Libro(ID)
    );

INSERT INTO Biblioteca (ID, Nombre) VALUES
(1, 'El lector');

INSERT INTO Empleado (ID, Nombre) VALUES
(1, 'Jose'),
(2, 'Raul'),
(3, 'Eduardo');

INSERT INTO Contrato_Empleado (ID, Inicio, Fin, IdEmpleado, IdBiblioteca) VALUES
(1, NOW(), '2027-09-27 18:00:00', 1, 1),
(2, '2026-07-15 16:00:00', '2027-03-24 16:00:00', 2, 1),
(3, '2026-08-08 16:00:00', '2027-06-19 16:00:00', 3, 1);

INSERT INTO Escritor (ID, Nombre) VALUES
(1, 'Jorge Luis Borges'),
(2, 'Jose Saramago'),
(3, 'Gabriela Cabezon Camara'),
(4, 'Homero'),
(5, 'Samanta Schweblin'),
(6, 'Roal Dahl'),
(7, 'Oscar Wilde');

INSERT INTO Libro (ID, Nombre, StockDisponible, IdEscritor) VALUES
(1, 'La Iliada', 15, 4),
(2, 'El Fantasma De Canterville', 20, 7),
(3, 'Matilda', 23, 6),
(4, 'Las Aventuras De La China Iron', 7, 3),
(5, 'Pajaros En La Boca', 13, 5),
(6, 'Las Brujas', 11, 6),
(7, 'La Odisea', 17, 4);

INSERT INTO Contrato_Libro (ID, Inicio, Fin, IdLibro, IdBiblioteca) VALUES
(1, '2005-04-25 12:00:00', '2030-09-25 12:00:00', 1, 1),
(2, '2008-06-18 14:00:00', '2028-08-11 14:00:00', 2, 1),
(3, '1998-02-28 17:00:00', '2032-05-23 17:00:00', 3, 1),
(4, '2011-09-13 19:00:00', '2029-11-29 19:00:00', 4, 1),
(5, '2014-05-10 22:00:00', '2035-10-08 22:00:00', 5, 1),
(6, '2011-04-01 19:00:00', '2018-12-22 19:00:00', 6, 1),
(7, '2014-06-30 22:00:00', '2022-08-16 22:00:00', 7, 1);

INSERT INTO Cliente (ID, Nombre) VALUES
(1, 'Salvador'),
(2, 'Alejandro'),
(3, 'Paula'),
(4, 'Matias'),
(5, 'Agustin'),
(6, 'Franco'),
(7, 'Sofia');

INSERT INTO Prestamo (ID, Inicio, Fin, IdCliente, IdLibro) VALUES
(1, '2026-04-25 12:00:00', '2026-05-25 12:00:00', 1, 3),
(2, '2025-06-18 14:00:00', '2025-07-18 14:00:00', 2, 2),
(3, '2024-02-28 17:00:00', '2024-03-28 17:00:00', 3, 5),
(4, '2023-09-13 19:00:00', '2023-10-13 19:00:00', 6, 1),
(5, '2022-05-10 22:00:00', '2022-06-10 22:00:00', 7, 4),
(6, '2021-07-24 11:00:00', '2021-08-24 11:00:00', 3, 4),
(7, '2020-01-17 07:00:00', '2020-02-17 07:00:00', 7, 3),
(8, '2019-12-02 15:00:00', '2020-01-02 15:00:00', 4, 3),
(9, '2018-03-30 16:00:00', '2018-04-30 16:00:00', 3, 2);

CREATE INDEX idx_cliente ON Cliente(ID);

CREATE INDEX idx_libro ON Libro(ID);

CREATE INDEX idx_escritor ON Escritor(ID);

CREATE VIEW Libro_escritor AS 
SELECT l.Nombre AS Nombre_libro, e.Nombre AS Nombre_escritor FROM Libro l
INNER JOIN Escritor e ON e.ID = l.IdEscritor;

SELECT * FROM Libro_escritor;

--Clientes que no tomaron prestado ningún libro

SELECT c.Nombre AS Nombre_cliente FROM Libro l
INNER JOIN Prestamo p ON p.IdLibro = l.ID
RIGHT JOIN Cliente c ON c.ID = p.IdCliente WHERE l.Nombre IS NULL;

--Libros que no fueron prestados

SELECT l.Nombre FROM Libro l
LEFT JOIN Prestamo p ON p.IdLibro = l.ID
WHERE p.IdCliente IS NULL;

--Escritores que no escribieron ningún libro

SELECT e.Nombre FROM Escritor e
LEFT JOIN Libro l ON e.ID = l.IdEscritor
WHERE l.Nombre IS NULL;

--Listar empleados de la biblioteca 1 

SELECT e.Nombre FROM Empleado e INNER JOIN Contrato_Empleado ce
ON ce.IdEmpleado = e.ID INNER JOIN Biblioteca b
ON b.ID = ce.IdBiblioteca WHERE b.ID = 1;

--Listar libros de la biblioteca 1 

SELECT l.Nombre FROM Libro l INNER JOIN Contrato_Libro cl
ON cl.IdLibro = l.ID INNER JOIN Biblioteca b
ON b.ID = cl.IdBiblioteca WHERE b.ID = 1;

--Cantidad de libros leidos por cada cliente

SELECT c.ID, c.Nombre, COUNT(p.IdLibro) FROM Libro l
INNER JOIN Prestamo p ON p.IdLibro = l.ID
RIGHT JOIN Cliente c ON c.ID = p.IdCliente
GROUP BY c.ID, c.Nombre ORDER BY COUNT(p.IdLibro) DESC;

--Escritores que escribieron un solo libro

SELECT e.ID, e.Nombre, COUNT(l.ID) FROM Libro l
RIGHT JOIN Escritor e ON e.ID = l.IdEscritor
GROUP BY e.ID, e.Nombre HAVING COUNT(l.ID) = 1;

--Cliente que más libros leyó

SELECT c.ID, c.Nombre, COUNT(p.IdLibro) FROM Libro l
INNER JOIN Prestamo p ON p.IdLibro = l.ID
RIGHT JOIN Cliente c ON c.ID = p.IdCliente
GROUP BY c.ID, c.Nombre ORDER BY COUNT(p.IdLibro) DESC LIMIT 1;

CREATE OR REPLACE FUNCTION libros_prestados_por_cliente(id_cli INT)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE cantidad INT;
BEGIN
    SELECT COUNT(*)
	INTO Cantidad
	FROM Prestamo
	WHERE IdCliente = id_cli;

	RETURN cantidad;

END;
$$;

SELECT libros_prestados_por_cliente(3);

CREATE OR REPLACE FUNCTION cantidad_de_libros_escritos(id_esc INT)
RETURNS INT
LANGUAGE plpgsql
AS $$
DECLARE cantidad INT;
BEGIN
    SELECT COUNT(*)
	INTO cantidad
	FROM Libro
	WHERE IdEscritor = id_esc;

	RETURN cantidad;

END;
$$;

SELECT cantidad_de_libros_escritos(4);

CREATE OR REPLACE PROCEDURE mostrar_empleados_biblioteca(id_bib INT)
LANGUAGE plpgsql
AS $$
DECLARE empleado_actual RECORD;
BEGIN
    FOR empleado_actual IN
	    SELECT e.ID, e.Nombre FROM Empleado e
	    INNER JOIN Contrato_Empleado ce
	    ON ce.IdEmpleado = e.ID
	    WHERE ce.IdBiblioteca = id_bib
		
	LOOP
        RAISE NOTICE 'ID: %, Nombre: %',
	        empleado_actual.ID,
		    empleado_actual.Nombre;
	END LOOP;

END;
$$;

CALL mostrar_empleados_biblioteca(1);

CREATE OR REPLACE PROCEDURE mostrar_libros_leidos_por_cliente(id_cli INT)
LANGUAGE plpgsql
AS $$
DECLARE libro_actual RECORD;
BEGIN
    FOR libro_actual IN
	  SELECT l.ID, l.Nombre FROM Libro l
	  INNER JOIN Prestamo p ON p.IdLibro = l.ID
	  WHERE p.IdCliente = id_cli

	LOOP
	  RAISE NOTICE 'ID: %, Nombre: %',
	    libro_actual.ID,
		libro_actual.Nombre;
	END LOOP;

END;
$$;

CALL mostrar_libros_leidos_por_cliente(3);

TRUNCATE TABLE Prestamo;

CREATE OR REPLACE FUNCTION actualizar_prestamo()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
	    UPDATE Libro
		SET StockPrestado = StockPrestado + 1
		WHERE NEW.IdLibro = ID;

		UPDATE Libro
		SET StockDisponible = StockDisponible - 1
		WHERE NEW.IdLibro = ID;
	END IF;

	IF TG_OP = 'DELETE' THEN
	    UPDATE Libro
		SET StockPrestado = StockPrestado - 1
		WHERE NEW.IdLibro = ID;

		UPDATE Libro
		SET StockDisponible = StockDisponible + 1
		WHERE NEW.IdLibro = ID;
	END IF;

	IF TG_OP = 'UPDATE' AND OLD.IdLibro <> NEW.IdLibro THEN
	
	    UPDATE Libro
		SET StockPrestado = StockPrestado - 1
		WHERE OLD.IdLibro = ID;

		UPDATE Libro
		SET StockPrestado = StockPrestado + 1
		WHERE NEW.IdLibro = ID;

		UPDATE Libro
		SET StockDisponible = StockDisponible + 1
		WHERE OLD.IdLibro = ID;

		UPDATE Libro
		SET StockDisponible = StockDisponible - 1
		WHERE NEW.IdLibro = ID;
	END IF;

	RETURN NULL;

END;
$$;

CREATE TRIGGER trg_actualizar_numeros
AFTER INSERT OR UPDATE OR DELETE
ON Prestamo
FOR EACH ROW
EXECUTE FUNCTION actualizar_prestamo();

INSERT INTO Prestamo (ID, Inicio, Fin, IdCliente, IdLibro) VALUES
(1, '2026-04-25 12:00:00', '2026-05-25 12:00:00', 1, 3),
(2, '2025-06-18 14:00:00', '2025-07-18 14:00:00', 2, 2),
(3, '2024-02-28 17:00:00', '2024-03-28 17:00:00', 3, 5),
(4, '2023-09-13 19:00:00', '2023-10-13 19:00:00', 6, 1),
(5, '2022-05-10 22:00:00', '2022-06-10 22:00:00', 7, 4),
(6, '2021-07-24 11:00:00', '2021-08-24 11:00:00', 3, 4),
(7, '2020-01-17 07:00:00', '2020-02-17 07:00:00', 7, 3),
(8, '2019-12-02 15:00:00', '2020-01-02 15:00:00', 4, 3),
(9, '2018-03-30 16:00:00', '2018-04-30 16:00:00', 3, 2);

SELECT * FROM Libro;

CREATE OR REPLACE FUNCTION verificar_vigencia()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE 
    FechaInicio TIMESTAMP;
	FechaFin TIMESTAMP;
BEGIN
    SELECT Inicio, Fin INTO FechaInicio, FechaFin FROM Contrato_Libro cl
	WHERE NEW.IdLibro = cl.IdLibro;

	IF (NEW.Inicio NOT BETWEEN FechaInicio AND FechaFin) OR 
	    (NEW.Fin NOT BETWEEN FechaInicio AND FechaFin) THEN
		RAISE EXCEPTION 'El libro % no está vigente en la biblioteca en esta fecha',
		    NEW.IdLibro;
	END IF;

	RETURN NEW;

END;
$$;

CREATE TRIGGER trg_verificar_si_esta_vigente
BEFORE INSERT OR UPDATE
ON Prestamo
FOR EACH ROW
EXECUTE FUNCTION verificar_vigencia();

--INSERT INTO Prestamo (ID, Inicio, Fin, IdCliente, IdLibro) VALUES
--(10, NOW(), '2027-01-25 12:00:00', 1, 6);

CREATE OR REPLACE FUNCTION impedir_eliminar_empleado_activo()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE 
    FechaInicio TIMESTAMP;
	FechaFin TIMESTAMP;
BEGIN
    SELECT Inicio, Fin INTO FechaInicio, FechaFin FROM Contrato_Empleado ce
	WHERE OLD.ID = ce.IdEmpleado;

	IF NOW() BETWEEN FechaInicio AND FechaFin THEN
	    RAISE EXCEPTION 'El empleado % aún se encuentra con contrato vigente',
		OLD.ID;
	END IF;

	RETURN OLD;

END;
$$;

CREATE TRIGGER trg_verificar_si_esta_activo
BEFORE DELETE
ON Empleado
FOR EACH ROW
EXECUTE FUNCTION impedir_eliminar_empleado_activo();

--DELETE FROM Empleado WHERE ID = 2;		

CREATE TABLE Auditoria_Prestamo(
    ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdPrestamo INT,
    Operacion VARCHAR(20),
    Fecha_inicio TIMESTAMP,
	Fecha_fin TIMESTAMP
);

TRUNCATE TABLE Prestamo;

CREATE OR REPLACE FUNCTION auditar_prestamo()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
	    INSERT INTO Auditoria_Prestamo (IdPrestamo, Operacion, Fecha_inicio, Fecha_fin) VALUES
		(NEW.ID, 'INSERT', NEW.Inicio, NEW.Fin);
	END IF;

	IF TG_OP = 'DELETE' THEN
	    INSERT INTO Auditoria_Prestamo (IdPrestamo, Operacion, Fecha_inicio, Fecha_fin) VALUES
		(OLD.ID, 'DELETE', OLD.Inicio, OLD.Fin);
	END IF;

	IF TG_OP = 'UPDATE' THEN
	    IF OLD.ID <> NEW.ID THEN
	        INSERT INTO Auditoria_Prestamo (IdPrestamo, Operacion, Fecha_inicio, Fecha_fin) VALUES
		    (NEW.ID, 'UPDATE', OLD.Inicio, OLD.Fin);
		END IF;
		IF OLD.Inicio <> NEW.Inicio AND OLD.Fin <> NEW.Fin THEN
	        INSERT INTO Auditoria_Prestamo (IdPrestamo, Operacion, Fecha_inicio, Fecha_fin) VALUES
		    (OLD.ID, 'UPDATE', NEW.Inicio, NEW.Fin);
		END IF;
		IF OLD.Inicio <> NEW.Inicio AND OLD.Inicio = NEW.Inicio THEN
	        INSERT INTO Auditoria_Prestamo (IdPrestamo, Operacion, Fecha_inicio, Fecha_fin) VALUES
		    (OLD.ID, 'UPDATE', NEW.Inicio, OLD.Fin);
		END IF;
		IF OLD.Fin <> NEW.Fin AND OLD.Fin = NEW.Fin THEN
	        INSERT INTO Auditoria_Prestamo (IdPrestamo, Operacion, Fecha_inicio, Fecha_fin) VALUES
		    (OLD.ID, 'UPDATE', OLD.Inicio, NEW.Fin);
		END IF;
	END IF;

    RETURN NULL;
	
END;
$$;

CREATE TRIGGER trg_auditar
AFTER INSERT OR UPDATE OR DELETE
ON Prestamo
FOR EACH ROW
EXECUTE FUNCTION auditar_prestamo();

INSERT INTO Prestamo (ID, Inicio, Fin, IdCliente, IdLibro) VALUES
(1, '2026-04-25 12:00:00', '2026-05-25 12:00:00', 1, 3),
(2, '2025-06-18 14:00:00', '2025-07-18 14:00:00', 2, 2),
(3, '2024-02-28 17:00:00', '2024-03-28 17:00:00', 3, 5),
(4, '2023-09-13 19:00:00', '2023-10-13 19:00:00', 6, 1),
(5, '2022-05-10 22:00:00', '2022-06-10 22:00:00', 7, 4),
(6, '2021-07-24 11:00:00', '2021-08-24 11:00:00', 3, 4),
(7, '2020-01-17 07:00:00', '2020-02-17 07:00:00', 7, 3),
(8, '2019-12-02 15:00:00', '2020-01-02 15:00:00', 4, 3),
(9, '2018-03-30 16:00:00', '2018-04-30 16:00:00', 3, 2);

UPDATE Prestamo
SET Inicio = '2020-01-01 11:00:00',
Fin = '2020-09-01 11:00:00'
WHERE ID = 8;

DELETE FROM Prestamo WHERE ID = 9;

SELECT * FROM Auditoria_Prestamo;
